# Generated by Django 5.2.1 on 2025-05-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Curso')),
                ('parallel', models.CharField(verbose_name='Paralelo')),
                ('stage', models.CharField(verbose_name='Etapa')),
                ('year', models.IntegerField(verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nombre(s)')),
                ('lname', models.TextField(max_length=100, verbose_name='Apellido(s)')),
                ('ci', models.BigIntegerField(verbose_name='Cédula de Identidad')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Teléfono')),
                ('email', models.TextField(null=True, verbose_name='Correo electrónico')),
                ('rude', models.BigIntegerField(verbose_name='Codigo RUDE')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Nombre(s)')),
                ('lname', models.TextField(max_length=100, verbose_name='Apellido(s)')),
                ('phone', models.BigIntegerField(null=True, verbose_name='Teléfono')),
                ('email', models.TextField(null=True, verbose_name='Correo electrónico')),
                ('ci', models.BigIntegerField(verbose_name='Cédula de Identidad')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Nota')),
                ('trimester', models.IntegerField(verbose_name='Trimestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Class_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.class', verbose_name='Clase')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Materia')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher', verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='class',
            name='homeroom_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.teacher', verbose_name='Docente'),
        ),
    ]
