# Generated by Django 5.2.1 on 2025-05-19 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(max_length=100, verbose_name='Login')),
                ('password', models.TextField(max_length=100, verbose_name='Password')),
                ('access_token', models.TextField(max_length=100, verbose_name='Access Token')),
                ('role', models.CharField(verbose_name='Role')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.student')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.teacher')),
            ],
        ),
    ]
