# Generated by Django 5.2.1 on 2025-05-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='homeroom_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.teacher', verbose_name='Docente'),
        ),
    ]
