# Generated by Django 5.2.1 on 2025-05-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_class_homeroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='title',
            field=models.TextField(default='test', verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
