# Generated by Django 5.2.1 on 2025-05-27 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_student_class_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='_class',
            field=models.ForeignKey(default=253, on_delete=django.db.models.deletion.CASCADE, to='backend.class', verbose_name='Clase'),
            preserve_default=False,
        ),
    ]
