# Generated by Django 5.2.1 on 2025-05-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_score__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='trimester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Trimestre'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('subject', 'student', '_class', 'trimester')},
        ),
    ]
