# Generated by Django 5.2.1 on 2025-05-27 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_score_trimester_alter_score_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.TextField(choices=[('present', 'Presente'), ('late', 'Tarde'), ('missed', 'Falta'), ('license', 'Licencia')], verbose_name='Estado')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.class', verbose_name='Clase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Materia')),
            ],
            options={
                'unique_together': {('subject', 'student', '_class', 'date')},
            },
        ),
    ]
