# Generated by Django 5.2.1 on 2025-05-27 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_assistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('score', models.IntegerField(default=100, verbose_name='Nota')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.class', verbose_name='Clase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Materia')),
            ],
        ),
    ]
