# Generated by Django 5.2.1 on 2025-05-27 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Descripcion'),
        ),
    ]
