# Generated by Django 5.2.1 on 2025-05-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_class_assignment',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='subject_class_assignment',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student_Class_Assignment',
        ),
        migrations.DeleteModel(
            name='Subject_Class_Assignment',
        ),
    ]
