# Generated by Django 5.2.1 on 2025-05-31 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_subject_class_assignment__class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='backend.student'),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.class', verbose_name='Clase')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Materia')),
            ],
            options={
                'unique_together': {('_class', 'subject', 'date')},
            },
        ),
    ]
