# Generated by Django 5.2.1 on 2025-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_class_students_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='status',
            field=models.TextField(choices=[('S', 'Acaba de empezar'), ('L', 'Llega tarde'), ('E', 'Terminó')], default='a', verbose_name='Estad0'),
            preserve_default=False,
        ),
    ]
