# Generated by Django 5.2.1 on 2025-05-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_classsession_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assistance',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.classsession', verbose_name='Clase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.TextField(choices=[('S', 'Acaba de empezar'), ('L', 'Llega tarde'), ('E', 'Terminó')], verbose_name='Estado'),
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='assistance',
            name='subject',
        ),
    ]
