# Generated by Django 5.2.1 on 2025-05-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_assistance_unique_together_assistance_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistance',
            unique_together={('student', 'session')},
        ),
    ]
