# Generated by Django 5.2.1 on 2025-05-31 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_assistance_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Titulo')),
            ],
        ),
        migrations.AlterField(
            model_name='assistance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='backend.student', verbose_name='Estudiante'),
        ),
    ]
