# Generated by Django 5.2.1 on 2025-05-31 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_subjectarea_alter_assistance_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.subjectarea', verbose_name='Area'),
            preserve_default=False,
        ),
    ]
