# Generated by Django 5.2.1 on 2025-06-02 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_subject_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.teacher', verbose_name='Docente'),
        ),
        migrations.CreateModel(
            name='ScoreTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Nota')),
                ('title', models.TextField(verbose_name='Título')),
                ('trimester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Trimestre')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.class', verbose_name='Clase')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject', verbose_name='Materia')),
            ],
        ),
    ]
