# Generated by Django 5.2.1 on 2025-06-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_subject_teacher_scoretarget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scoretarget',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.scoretarget', verbose_name='Tarea'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='score',
            name='_class',
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='score',
            name='trimester',
        ),
    ]
