# Generated by Django 5.2.1 on 2025-06-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_score_unique_together_remove_scoretarget_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'target')},
        ),
    ]
