# Generated by Django 5.2.1 on 2025-06-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_score_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(max_length=256, verbose_name='Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', verbose_name='Usuario')),
            ],
        ),
    ]
