# Generated by Django 5.2.1 on 2025-06-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_fcm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcm',
            unique_together={('user', 'token')},
        ),
    ]
