# Generated by Django 5.2.1 on 2025-06-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_fcm_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name='Usuario')),
                ('role', models.TextField(verbose_name='Rol')),
                ('login', models.TextField(verbose_name='Login')),
                ('action', models.TextField(verbose_name='Acción')),
                ('ip', models.TextField(verbose_name='IP')),
                ('time', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
        ),
    ]
