# Generated by Django 5.2.1 on 2025-06-02 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoretarget',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
