# Generated by Django 5.2.1 on 2025-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_scoretarget_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(verbose_name='Parametros')),
                ('title', models.TextField(verbose_name='Título')),
                ('time', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
        ),
    ]
