# Generated by Django 5.2.1 on 2025-05-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Registro')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lname', models.CharField(max_length=100, verbose_name='Apeliido')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('access_token', models.CharField(max_length=255, unique=True, verbose_name='Token de acceso')),
            ],
        ),
    ]
